
title: Trabajo Fin de Máster
longtitle: Trabajo Fin de Máster
email: mddasil@posgrado.upv.es
description: >- 
  Contenedores y microservicios para IoT: 
  Demostración de cómo el uso de tecnología de contenedores y las prácticas 
  de microservicios pueden mejorar la gestión de dispositivos en el control 
  del tráfico en ciudades inteligentes.
baseurl: "/documentation"
url: "https://upv-tfm-iot.github.io"
domain: upv-tfm-iot.github.io
twitter_username: marcelodedebora
github_username:  marcelomrwin

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

toc:
  enabled: true

version: 1.0
gitbook_version: 3.2.3

rss: RSS

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts
  - README.md
  - .gitignore

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - posts
  - others

destination: ./_site
incremental: false
regenerate:  true